### PR TITLE
Add first version of software documentation page

### PR DESCRIPTION
**Pull request by azza-max**

### CODE REVIEW

**Comment by dgarijo** [comment]
@azza-max thanks a lot on this PR.
I see we have a page on creating a readthedocs: https://everse.software/RSQKit/creating_readthedocs
We have to figure out how to homogenize this content.

**Comment by azza-max** [comment]
Hello @dgarijo, thanks! I've cited 'readthedocs' as a tool/material. Perhaps we could also cite the 'creating_readthedocs' page, since I've covered more general aspects beyond just using readthedocs as a tool. If not, I'll try merging both pieces of content into a single page. What do you think ?

**Comment by dgarijo** [comment]
I like this page because it's more comprehensive than the one on readthedocs. Maybe we can have this one as base and the other one as an example for readthedocs alone? And then, remove the duplicated content.

**Review by anenadic — APPROVED** [review]
Thank you very much @azza-max for your work on this PR and the related on on readthedocs.

**Comment by azza-max** [comment]
> Thank you very much @azza-max for your work on this PR and the related on on readthedocs.
Thanks Aleksandra, for reviewing and approving 😊

**Pull request merged**
