### PR TITLE
addition of REUSE to license task

### PR DESCRIPTION
**Pull request by vuillaut**
Changes proposed in this pull request:

* add REUSE recommendation in case of multiple licenses

### CODE REVIEW

**Comment by dgarijo** [comment]
Thanks @vuillaut. We need to adapt the tools so the section is built automagically. Would it make sense to add REUSE in tools and resources as well? Is it a tool or guidelines?

**Comment by vuillaut** [comment]
> Thanks @vuillaut. We need to adapt the tools so the section is built automagically. Would it make sense to add REUSE in tools and resources as well? Is it a tool or guidelines?

REUSE is a recommendation with specifications, but they also have a tool to check compliance to these specifications.

Ok, the way to mention tools is already in production? Otherwise I can wait and update this PR later.

**Comment by dgarijo** [comment]
It's in draft: https://github.com/EVERSE-ResearchSoftware/RSQKit/pull/173
Would it be ok to wait until we push it?

**Comment by vuillaut** [comment]
> Would it be ok to wait until we push it?

sure! nothing urgent here

**Comment by dgarijo** [comment]
After the meeting today (sprint). It was decided to merge and later fix

**Pull request merged**
