### PR TITLE
add Matomo analytics

### LINKED ISSUE #97: Add analytics
Like the main website (https://github.com/EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io/issues/25), we want analytics on this page as well. We'll want to use the same solution for both websites, so we can keep discussion in the issue for the main website, but just adding this issue here as well to make sure we don't forget.

This was also an action point coming out of the editorial board meeting today.

### PR DESCRIPTION
**Pull request by egpbos**
Fixes #97.

Changes proposed in this pull request:

* Activate Matomo analytics (using the NLeSC Matomo server). This thankfully is implemented in the [elixir-toolkit-theme](https://github.com/ELIXIR-Belgium/elixir-toolkit-theme) already, so we only need to add two lines in config.yml!
* Add privacy policy. I was going to copy the one for the EVERSE main site introduced in https://github.com/EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io/pull/70, but may want to also take some inspiration from the RDMkit one: https://github.com/elixir-europe/rdmkit/blob/master/pages/about/privacy.md?plain=1

Notes for reviewers: 

* ~I did not add the privacy policy yet, so please don't merge yet! I opened the PR to be able to test the build on Netlify.~
* Ready for review!

### CODE REVIEW

**Comment by egpbos** [comment]
The Matomo tag does not show up in the Netlify build. This is because apparently it does not build in Jekyll "production mode". The analytics tags are disabled outside of production mode in ETT. I tested locally, and there it does work.

Will now continue with the privacy policy.

**Comment by egpbos** [comment]
The following page lists 12 steps to be taken for a cookieless GDPR compliant site: https://matomo.org/faq/new-to-piwik/how-do-i-use-matomo-analytics-without-consent-or-cookie-banner/

I think we only strictly need to do step 1, which is to add a single line of Javascript that disables cookies, and step 12, adding a privacy policy (that can be copied from the main EVERSE site).

In addition, a "recommended" step is to provide a Matomo opt-out button (step 11 in the list). I think the main EVERSE website also tried to do that, but on my browser I cannot actually find it anywhere. @graeme-a-stewart is that expected?

The other steps should be configured in the NLeSC Matomo instance already, because it was setup with GDPR compliance.

**Comment by egpbos** [comment]
Ready for review! As noted above, Matomo doesn't actually work on Netlify, so you'll have to build on your laptop to test if you like. I also did so, and it is working for me, so you can also trust me on that and see how that works out ;)

**Comment by egpbos** [comment]
@graeme-a-stewart: I modified the privacy text slightly. Matomo does still create cookies, but the important part is that no personally identifiable info is included in them (see the "Essential blabla" section here: https://matomo.org/faq/general/faq_157). Doesn't really matter much for privacy purposes, I think, but just a minor edit for completeness.

**Review by anenadic — APPROVED** [review]

**Comment by graeme-a-stewart** [comment]
> In addition, a "recommended" step is to provide a Matomo opt-out button (step 11 in the list). I think the main EVERSE website also tried to do that, but on my browser I cannot actually find it anywhere. @graeme-a-stewart is that expected?
> 

There was some JS support for that in the Hugo Matomo plugin, however I failed to get it to work and time pressure led to me putting that on a back burner. I also didn't managed to get any cookie set to signal the user's choice.  Did you managed to get it functional in the end? It was all a bit fiddly with the popup that allowed the user to set the opt out.

**Comment by graeme-a-stewart** [comment]
> @graeme-a-stewart: I modified the privacy text slightly. Matomo does still create cookies, but the important part is that no personally identifiable info is included in them (see the "Essential blabla" section here: https://matomo.org/faq/general/faq_157). Doesn't really matter much for privacy purposes, I think, but just a minor edit for completeness.

I actually can't find any cookies set from Matomo, but we will update the everse.software privacy policy - thanks for clarifying.

**Comment by egpbos** [comment]
> > In addition, a "recommended" step is to provide a Matomo opt-out button (step 11 in the list). I think the main EVERSE website also tried to do that, but on my browser I cannot actually find it anywhere. @graeme-a-stewart is that expected?
> 
> There was some JS support for that in the Hugo Matomo plugin, however I failed to get it to work and time pressure led to me putting that on a back burner. I also didn't managed to get any cookie set to signal the user's choice. Did you managed to get it functional in the end? It was all a bit fiddly with the popup that allowed the user to set the opt out.

Yes, it works in the end: https://everse.software/RSQKit/privacy. I just added the opt-out HTML directly to the markdown file. Jekyll preserves this, apparently. It doesn't work in all frameworks though (I had less luck doing the same in Docsify), so ymmv for Hugo.

**Pull request merged**
